### ISSUE TITLE
[BUG] Browser Toolkit: Multi Crawler Tool Fails with Validation Error

### ISSUE THREAD

**Issue by epamLDadayan** [ProjectAlita/projectalita.github.io#490] opened 2024-09-19 05:37 UTC
**Description:**
The Multi Crawler tool in the Browser Toolkit fails with a validation error when attempting to execute a user query to gather information from several web pages. This issue occurs across any Agent framework (OpenAI, ReAct, etc.).

**Steps to Reproduce:**
1. Create an agent with proper instructions.
2. Add the Browser Toolkit.
3. Select the Multi Crawler tool.
4. Provide a user query to gather information from several web pages.
5. Execute the query.

**Actual Result:**
The Multi Crawler tool fails with the following error:
```
Traceback (most recent call last):
  File "/tmp/tmprm9by_s0/lib/python3.10/site-packages/langchain_core/tools/base.py", line 549, in run
    tool_args, tool_kwargs = self._to_args_and_kwargs(tool_input)
  File "/tmp/tmprm9by_s0/lib/python3.10/site-packages/langchain_core/tools/base.py", line 472, in _to_args_and_kwargs
    tool_input = self._parse_input(tool_input)
  File "/tmp/tmprm9by_s0/lib/python3.10/site-packages/langchain_core/tools/base.py", line 424, in _parse_input
    result = input_args.parse_obj(tool_input)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MultiURLCrawlerModel
urls
  str type expected (type=type_error.str)
```

**Expected Result:**
The Multi Crawler tool should work without issues, successfully gathering information from multiple web pages as specified in the user query.

**Notes:**
- This issue is reproducible across any Agent framework (OpenAI, ReAct, etc.).
- Below are the Agent's and User's instructions used during the test:

**Agent's Instructions:**
```
### Role: 
You are an expert AI bot with huge experience in AI, Software Testing, Web Browsing (scraping), and Google Search Engine.

### Task:
Your main task is to respond to user's queries and fulfill user's orders.

### GitHub:
- Use Browser toolkit to find issues and their content.
- You have all required permissions and accesses to the Web.
```

**User's Instructions:**
```
Role: You are a football enthusiast and journalist.
Task:
1. Review the articles about Bayer04 miracle season using the Browser toolkit and selecting the top 5 articles.
2. Then analyze the selected articles.
3. Using your own vision and approach, create a new article about Bayer04 season. The article must be not more than 200 words, highlighting their success, main players, and coach's work as well as fan support.
4. Provide the article in markdown format.
### Constraints:
- Ensure communication is professional, employing standard software testing terminologies while providing accessible explanations.
```

![Image](https://github.com/user-attachments/assets/a91f13ab-7fc0-4ca2-abce-5bf1762667b9)

**Comment by plageat** [comment] 2024-11-20 12:04
Looks like **MultiURLCrawlerModel** is getting **List[str]** for urls, while PD model expects urls to be of **str** type.
Probably, @arozumenko knows much better how to fix it correctly not introducing regressions

Here is related indexer logs for the case

```json
{
  "thoughts": {
    "text": "I have used the multi_url_crawler tool to search for articles about Bayer04 miracle season and selected the top 2 articles. Here are the URLs of the selected articles:\n\n1. [Article 1](https://www.example.com/article1)\n2. [Article 2](https://www.example.com/article2)\n\nNow, I will analyze the selected articles and create a new article about Bayer04 season. Finally, I will provide the article in markdown format.",
    "plan": "1. Use the multi_url_crawler tool to search for articles about Bayer04 miracle season and select the top 2 articles.\n2. Analyze the selected articles.\n3. Create a new article about Bayer04 season.\n4. Provide the article in markdown format."
  },
  "tool": {
    "name": "multi_url_crawler",
    "args": {
      "query": "Bayer04 miracle season",
      "urls": [
        "https://www.example.com/article1",
        "https://www.example.com/article2"
      ]
    }
  }
}
```

**Comment by MikalaiB** [comment] 2024-11-29 17:37
Fixed in alita-tools 0.1.8

**Comment by epamLDadayan** [comment] 2024-12-02 06:57
@MikalaiB , is it deployed on Main env?

still getting the error:

Input should be a valid string [type=string_type, input_value=['https://www.espn.com', ...eguardian.com/football'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type

**Comment by MikalaiB** [comment] 2024-12-02 08:21
@epamLDadayan 
It was my fault,
Now it is on main (tools 0.1.9)
<img width="1468" alt="image" src="https://github.com/user-attachments/assets/6cbba641-de46-4cea-8fe1-2a9ddb9b6497">

**Closed** 2024-12-03 09:02 UTC
Labels: Agent_issue
